# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cards.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_cards.ipynb 3
suits = ["club", "diamond", "heart", "spade"]
ranks = [None, "A"] + [str(n) for n in range(2,11)] + ["J","Q","K"]

# %% ../nbs/00_cards.ipynb 5
class Card:
    "more documentation with `emphasis`"
    def __init__(self, 
                 suit, #an index into 'suite'
                 rank):
        self.suit,self.rank = suit,rank
    def __str__(self): return f"rank: {ranks[self.rank]}, suite: {suits[self.suit]}"
    __repr__ = __str__
    def __eq__(self, a:'Card'): return (self.suit, self.rank)==(a.suit,a.rank)

# %% ../nbs/00_cards.ipynb 11
@utils.patch
def __eq__(self:Card, a:Card): return (self.suit,self.rank)==(a.suit,a.rank)
@utils.patch
def __lt__(self:Card, a:Card): return (self.suit,self.rank)<(a.suit,a.rank)
@utils.patch
def __gt__(self:Card, a:Card): return (self.suit,self.rank)>(a.suit,a.rank)
